  name: Execute tests

  on:
    push:
      branches: [ master ]
    pull_request:
      branches: [ master ]       

  jobs:
    execute-tests:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Run maven commands
          uses: actions/setup-java@av2
          with:
            commands: 'mvn package'

